[package]

name = "benchmark"
version = "0.0.0"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>"  ]
build = "build.rs"

[[bin]]

name = "benchmark"
path = "benchmark.rs"


[build-dependencies.capnpc]
path = "../"

[dependencies]
capnp = "0.0.18"
