dist: trusty
sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
  - 1.16.0
env:
  global:
    - export PATH="$PATH:$HOME/bin"
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/lib"
addons:
  apt:
    packages:
      - gcc
      - g++
install:
  - curl -O https://capnproto.org/capnproto-c++-0.5.3.tar.gz
  - tar zxf capnproto-c++-0.5.3.tar.gz
  - cd capnproto-c++-0.5.3
  - ./configure --prefix=$HOME
  - make -j3
  - make install
  - cd ../

script:
  - cargo build
  - cargo test
  - cargo doc
  - cargo clean
  - cargo build --features rpc
  - cargo test --features rpc
  - cargo doc --features rpc
  - cd test
  - cargo test
  - cargo test --release
  - cd ..
  - cd example/addressbook
  - cargo build
  - ./target/debug/addressbook write | ./target/debug/addressbook read
  - cd ../..
  - cd benchmark
  - cargo build --release
  - ./target/release/run_all target/release/benchmark

