[package]
name = "capnp-futures"
version = "0.13.0-alpha"
authors = [ "David Renshaw <drenshaw@gmail.com>" ]
license = "MIT"

description = "async serialization for Cap'n Proto messages"
repository = "https://github.com/dwrensha/capnproto-rust"
documentation = "https://docs.capnproto-rust.org/capnp_futures/"
edition = "2018"

keywords = ["async"]

[dependencies]
capnp = { version = "0.13.0-alpha", path = "../capnp" }
futures = "0.3.0"

[dev-dependencies]
capnp = { version = "0.13.0-alpha", path = "../capnp", features = ["quickcheck"] }
quickcheck = "0.9"
