[package]
name = "capnp-futures"
version = "0.1.1"
authors = [ "David Renshaw <drenshaw@gmail.com>" ]
license = "MIT"

description = "async serialization for Cap'n Proto messages"
repository = "https://github.com/dwrensha/capnproto-rust"
documentation = "https://docs.capnproto-rust.org/capnp_futures/"

keywords = ["async"]

[dependencies]

byteorder = "1.0"
capnp = { version = "0.8", path = "../capnp" }
futures = "0.1.12"

[dev-dependencies]
capnp = { version = "0.8", path = "../capnp", features = ["quickcheck"] }
quickcheck = "0.2"
