[package]

name = "calculator"
version = "0.0.0"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>"  ]
build = "build.rs"
edition = "2018"

[[bin]]

name = "calculator"
path = "main.rs"

[build-dependencies]
capnpc = { path = "../../../capnpc" }

[dependencies]
capnp = { path = "../../../capnp" }
futures-preview = "0.3.0-alpha.18"
romio = "0.3.0-alpha.9"

[dependencies.capnp-rpc]
path = "../.."
